# -*- coding: utf-8 -*-
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

##### Vos Configurations
  # Nom de la VM
  config.vm.hostname = "VM36NetworkProject"
  # "box" préinstallée de base
  config.vm.box = "debian-tp"

  # Ajout d'une interface réseau (privée)
  config.vm.network "private_network", ip:"0.0.0.0", auto_config: false, virtualbox__intnet: "LAN2_6" 
  config.vm.network "private_network", ip:"0.0.0.0", auto_config: false, virtualbox__intnet: "LAN4" 

##### NE PAS MODIFIER CETTE PARTIE

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.vm.synced_folder ".", "/vagrant", owner: "etu"
  config.vm.synced_folder "../partage", "/mnt/partage", create: true, owner: "etu" 

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

end
